task fp2 completed
EvSedov/study pull request #3
Opened 2021-04-18 17:22 UTC by EvSedov

2021-04-19 10:19 UTC, Andrew8xx8 requested changes

2021-04-19 10:19 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +        for item in self
`each` нужно реальзовать используя рекурсию

2021-04-19 10:19 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +        new_array = []
`compact` нужно реализовать через `reduce`

2021-04-19 10:19 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +        new_array = self
Довольно сложный код. В целом `reduce` нужно реализовать используя рекурсию, должно стать проще

2021-04-19 19:56 UTC, Andrew8xx8 requested changes

2021-04-19 19:56 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +        my_each_recurs = lambda { |elements, &fn|
Зачем здесь лямбда? Это лишнее, можно ее просто убрать.

2021-04-19 19:56 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +        my_reduce_recurs = lambda { |elements, acc, &fn|
Тут тоже теперь лишняя лямбда

2021-04-21 13:27 UTC, EvSedov commented on test/exercise/fp2/solution.rb
> +        my_each_recurs = lambda { |elements, &fn|
Честно говоря не очень понял как без лямбды можно вернуть первоначальный self. Сделал через вложенный метод, чтобы как-то сохранить этот self, но что-то мне подсказывает, что не так нужно было сделать ))

2021-04-23 14:35 UTC, nut4k1 commented on test/exercise/fp2/solution.rb
> +        my_each_recurs = lambda { |elements, &fn|
просто `self`?

2021-04-23 14:36 UTC, nut4k1 requested changes

2021-04-23 14:36 UTC, nut4k1 commented on test/exercise/fp2/solution.rb
> +        end
не окей функции в функции объявлять

2021-04-23 14:36 UTC, nut4k1 commented on test/exercise/fp2/solution.rb
> +        my_each_recurs(new_array, &func)
возвращать self надо

2021-04-24 04:31 UTC, EvSedov commented on test/exercise/fp2/solution.rb
> +        my_each_recurs(new_array, &func)
это влияние JS )))

2021-04-24 04:32 UTC, EvSedov commented on test/exercise/fp2/solution.rb
> +        end
я вот почему-то именно так и думал, что это не гуд...

2021-04-26 09:00 UTC, Andrew8xx8 approved these changes

2021-04-26 09:06 UTC, merged